# Generated by Django 5.0.14 on 2025-06-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('enterprise', 'Enterprise perm'), ('pro', 'Pro perm'), ('basic', 'Basic perm'), ('free', 'Free perm')]},
        ),
    ]
